# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pcf-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-  
      if: steps.npm-cache.outputs.cache-hit != 'true'          
    - name: Install npm packages
      run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: MSBuild
      working-directory: Solution/PCFQRCode
      run: msbuild /restore /t:rebuild
    - name: Check npm version
      id: versioncheck
      uses: kriasoft/check-version@v1
      with:
        format: "PCFQRCode_v{version}"
    - uses: actions/upload-artifact@v2
      with:
        name: ${{steps.versioncheck.outputs.release}}_managed.zip
        path: Solution/PCFQRCode/bin/Debug/PCFQRCode_managed.zip
    - uses: actions/upload-artifact@v2
      with:
        name: ${{steps.versioncheck.outputs.release}}_unmanaged.zip
        path: Solution/PCFQRCode/bin/Debug/PCFQRCode.zip
